export const data: any = [
  {
    createdAt: "2021-11-16T19:35:19Z",
    priceRange: { maxVariantPrice: 7300, minVariantPrice: 6800 },
    slug: { current: "anillo-loretta", _type: "slug" },
    title: "ANILLO LORETTA",
    vendor: "Mariëtte Jewelry",
    descriptionHtml:
      '<p>Este delicado anillo se conforma por una esmeralda corte asscher montada en oro de 14K acompañada con dos diamantes blancos.</p>\n<p>Disponible oro amarillo, blanco o rosa de 14K.</p>\n<p class="p1"><strong>Este anillo lo tenemos en stock en Oro Amarillo 14K, en talla #6,</strong> por lo cual el envío se realizará de 2 a 3 días hábiles.</p>\n<p class="p1">En caso de necesitar otra talla se producirá una nueva pieza a tu medida. Por favor toma en cuenta que podemos tardar aproximadamente de <strong>10 a 15 días hábiles</strong> en tener listo tu pedido.<br></p>\n<p class="p1"><span class="s1"></span><span class="s1">Todas nuestras piezas son elaboradas con piedras naturales, por lo tanto, el color de las piedras <strong>puede variar</strong> de una pieza otra.</span></p>\n<p class="p1">Para diseñar tu anillo, puedes escribirnos por WhatsApp al +52 (33) 3333 3333.</p>',
    gid: "gid://shopify/Product/7448400068827",
    isDeleted: false,
    options: [
      {
        _type: "option",
        name: "Metal",
        _key: "Metal",
        values: ["Oro Amarillo 14K", "Oro Blanco 14K", "Oro Rosa 14K"],
      },
      {
        values: [
          "4",
          "4.5",
          "5",
          "5.5",
          "6",
          "6.5",
          "7",
          "7.5",
          "8",
          "8.5",
          "9",
        ],
        _type: "option",
        name: "Talla",
        _key: "Talla",
      },
    ],
    productType: "Anillos",
    tags: "Anillo, Anillos, Diamantes, Esmeralda",
    variants: [
      { data: { option1: "Oro Amarillo 14K", option2: "4" } },
      { data: { option2: "4.5", option1: "Oro Amarillo 14K" } },
      { data: { option1: "Oro Amarillo 14K", option2: "5" } },
      { data: { option1: "Oro Amarillo 14K", option2: "5.5" } },
      { data: { option1: "Oro Amarillo 14K", option2: "6" } },
      { data: { option1: "Oro Amarillo 14K", option2: "6.5" } },
      { data: { option1: "Oro Amarillo 14K", option2: "7" } },
      { data: { option1: "Oro Amarillo 14K", option2: "7.5" } },
      { data: { option1: "Oro Amarillo 14K", option2: "8" } },
      { data: { option1: "Oro Amarillo 14K", option2: "8.5" } },
      { data: { option1: "Oro Amarillo 14K", option2: "9" } },
      { data: { option1: "Oro Blanco 14K", option2: "4" } },
      { data: { option1: "Oro Blanco 14K", option2: "4.5" } },
      { data: { option1: "Oro Blanco 14K", option2: "5" } },
      { data: { option1: "Oro Blanco 14K", option2: "5.5" } },
      { data: { option1: "Oro Blanco 14K", option2: "6" } },
      { data: { option1: "Oro Blanco 14K", option2: "6.5" } },
      { data: { option1: "Oro Blanco 14K", option2: "7" } },
      { data: { option2: "7.5", option1: "Oro Blanco 14K" } },
      { data: { option1: "Oro Blanco 14K", option2: "8" } },
      { data: { option1: "Oro Blanco 14K", option2: "8.5" } },
      { data: { option1: "Oro Blanco 14K", option2: "9" } },
      { data: { option1: "Oro Rosa 14K", option2: "4" } },
      { data: { option1: "Oro Rosa 14K", option2: "4.5" } },
      { data: { option2: "5", option1: "Oro Rosa 14K" } },
      { data: { option1: "Oro Rosa 14K", option2: "5.5" } },
      { data: { option1: "Oro Rosa 14K", option2: "6" } },
      { data: { option1: "Oro Rosa 14K", option2: "6.5" } },
      { data: { option1: "Oro Rosa 14K", option2: "7" } },
      { data: { option1: "Oro Rosa 14K", option2: "7.5" } },
      { data: { option1: "Oro Rosa 14K", option2: "8" } },
      { data: { option1: "Oro Rosa 14K", option2: "8.5" } },
      { data: { option1: "Oro Rosa 14K", option2: "9" } },
    ],
    id: 7448400068827,
    previewImageUrl:
      "https://cdn.shopify.com/s/files/1/0612/8087/8811/products/DSC_0771.png?v=1637091333",
    status: "active",
  },
  {
    gid: "gid://shopify/Product/8027882356955",
    productType: "Anillos",
    status: "active",
    vendor: "Mariëtte Jewelry",
    id: 8027882356955,
    slug: { _type: "slug", current: "articulo-amira" },
    createdAt: "2023-05-11T23:59:20Z",
    descriptionHtml:
      '<meta charset="utf-8">\n<p>Elegante y sofisticado, nuestro anillo Amira es ideal para llevarlo a diario. La esmeralda engastada en bisel elevado permite que la luz entre por debajo de la gema, dando como resultado un impresionante despliegue de color que sin duda llamará la atención.</p>\n<p>Amira es perfecto para quienes prefieren una presencia delicada con un toque moderno, realzará cualquier atuendo.</p>\n<p>Nuestras piezas están hechas a mano, por lo que te pedimos tomar en cuenta un tiempo de producción de 3 – 5 semanas. Revisamos cada una de nuestras piezas y nos aseguramos de que cumplan con nuestros estándares de calidad.</p>\n<p>Utilizamos piedras naturales, por lo que el color de una pieza a otra puede variar ligeramente.</p>',
    previewImageUrl:
      "https://cdn.shopify.com/s/files/1/0612/8087/8811/files/AMIRA4.jpg?v=1684376675",
    priceRange: { maxVariantPrice: 6700, minVariantPrice: 2800 },
    title: "ANILLO 'AMIRA'",
    isDeleted: false,
    options: [
      {
        _key: "Metal",
        values: [
          "Oro Amarillo 14K",
          "Oro Blanco 14K",
          "Oro Rosado 14K",
          "Plata",
        ],
        _type: "option",
        name: "Metal",
      },
      {
        values: [
          "4",
          "4.5",
          "5",
          "5.5",
          "6",
          "6.5",
          "7",
          "7.5",
          "8",
          "8.5",
          "9",
        ],
        _type: "option",
        name: "Talla",
        _key: "Talla",
      },
    ],
    tags: "Anillos",
    variants: [
      { data: { option2: "4", option1: "Oro Amarillo 14K" } },
      { data: { option1: "Oro Amarillo 14K", option2: "4.5" } },
      { data: { option1: "Oro Amarillo 14K", option2: "5" } },
      { data: { option1: "Oro Amarillo 14K", option2: "5.5" } },
      { data: { option1: "Oro Amarillo 14K", option2: "6" } },
      { data: { option1: "Oro Amarillo 14K", option2: "6.5" } },
      { data: { option1: "Oro Amarillo 14K", option2: "7" } },
      { data: { option2: "7.5", option1: "Oro Amarillo 14K" } },
      { data: { option1: "Oro Amarillo 14K", option2: "8" } },
      { data: { option1: "Oro Amarillo 14K", option2: "8.5" } },
      { data: { option1: "Oro Amarillo 14K", option2: "9" } },
      { data: { option1: "Oro Blanco 14K", option2: "4" } },
      { data: { option1: "Oro Blanco 14K", option2: "4.5" } },
      { data: { option1: "Oro Blanco 14K", option2: "5" } },
      { data: { option1: "Oro Blanco 14K", option2: "5.5" } },
      { data: { option1: "Oro Blanco 14K", option2: "6" } },
      { data: { option1: "Oro Blanco 14K", option2: "6.5" } },
      { data: { option1: "Oro Blanco 14K", option2: "7" } },
      { data: { option1: "Oro Blanco 14K", option2: "7.5" } },
      { data: { option1: "Oro Blanco 14K", option2: "8" } },
      { data: { option1: "Oro Blanco 14K", option2: "8.5" } },
      { data: { option1: "Oro Blanco 14K", option2: "9" } },
      { data: { option1: "Oro Rosado 14K", option2: "4" } },
      { data: { option1: "Oro Rosado 14K", option2: "4.5" } },
      { data: { option1: "Oro Rosado 14K", option2: "5" } },
      { data: { option2: "5.5", option1: "Oro Rosado 14K" } },
      { data: { option1: "Oro Rosado 14K", option2: "6" } },
      { data: { option1: "Oro Rosado 14K", option2: "6.5" } },
      { data: { option1: "Oro Rosado 14K", option2: "7" } },
      { data: { option1: "Oro Rosado 14K", option2: "7.5" } },
      { data: { option1: "Oro Rosado 14K", option2: "8" } },
      { data: { option1: "Oro Rosado 14K", option2: "8.5" } },
      { data: { option1: "Oro Rosado 14K", option2: "9" } },
      { data: { option1: "Plata", option2: "4" } },
      { data: { option1: "Plata", option2: "4.5" } },
      { data: { option1: "Plata", option2: "5" } },
      { data: { option1: "Plata", option2: "5.5" } },
      { data: { option1: "Plata", option2: "6" } },
      { data: { option1: "Plata", option2: "6.5" } },
      { data: { option1: "Plata", option2: "7" } },
      { data: { option1: "Plata", option2: "7.5" } },
      { data: { option1: "Plata", option2: "8" } },
      { data: { option1: "Plata", option2: "8.5" } },
      { data: { option1: "Plata", option2: "9" } },
    ],
  },
  {
    gid: "gid://shopify/Product/8030806409435",
    isDeleted: false,
    slug: { current: "anillo-ana", _type: "slug" },
    previewImageUrl:
      "https://cdn.shopify.com/s/files/1/0612/8087/8811/files/ANA1.jpg?v=1684374516",
    productType: "Anillos",
    vendor: "Mariëtte Jewelry",
    descriptionHtml:
      '<meta charset="utf-8">\n<p>Un diseño sencillo que muestra el hermoso brillo y fuego de la moissanita. Las moissanitas laterales complementan la piedra central para crear un aspecto moderno y clásico que es apropiado para muchas ocasiones.</p>\n<p>Nuestras piezas están hechas a mano, por lo que te pedimos tomar en cuenta un tiempo de producción de 3 – 5 semanas. Revisamos cada una de nuestras piezas y nos aseguramos de que cumplan con nuestros estándares de calidad.</p>',
    id: 8030806409435,
    options: [
      {
        values: ["Oro Blanco 14K", "Oro Amarillo 14K", "Oro Rosa 14k", "Plata"],
        _type: "option",
        name: "Metal",
        _key: "Metal",
      },
      {
        name: "Talla",
        _key: "Talla",
        values: [
          "4",
          "4.5",
          "5",
          "5.5",
          "6",
          "6.5",
          "7",
          "7.5",
          "8",
          "8.5",
          "9",
        ],
        _type: "option",
      },
    ],
    status: "active",
    tags: "Anillos",
    title: "ANILLO ‘ANA’",
    createdAt: "2023-05-17T06:32:13Z",
    priceRange: { maxVariantPrice: 6900, minVariantPrice: 3800 },
    variants: [
      { data: { option1: "Oro Blanco 14K", option2: "4" } },
      { data: { option1: "Oro Blanco 14K", option2: "4.5" } },
      { data: { option2: "5", option1: "Oro Blanco 14K" } },
      { data: { option1: "Oro Blanco 14K", option2: "5.5" } },
      { data: { option1: "Oro Blanco 14K", option2: "6" } },
      { data: { option1: "Oro Blanco 14K", option2: "6.5" } },
      { data: { option1: "Oro Blanco 14K", option2: "7" } },
      { data: { option1: "Oro Blanco 14K", option2: "7.5" } },
      { data: { option1: "Oro Blanco 14K", option2: "8" } },
      { data: { option1: "Oro Blanco 14K", option2: "8.5" } },
      { data: { option1: "Oro Blanco 14K", option2: "9" } },
      { data: { option1: "Oro Amarillo 14K", option2: "4" } },
      { data: { option1: "Oro Amarillo 14K", option2: "4.5" } },
      { data: { option1: "Oro Amarillo 14K", option2: "5" } },
      { data: { option2: "5.5", option1: "Oro Amarillo 14K" } },
      { data: { option1: "Oro Amarillo 14K", option2: "6" } },
      { data: { option2: "6.5", option1: "Oro Amarillo 14K" } },
      { data: { option1: "Oro Amarillo 14K", option2: "7" } },
      { data: { option1: "Oro Amarillo 14K", option2: "7.5" } },
      { data: { option1: "Oro Amarillo 14K", option2: "8" } },
      { data: { option1: "Oro Amarillo 14K", option2: "8.5" } },
      { data: { option1: "Oro Amarillo 14K", option2: "9" } },
      { data: { option2: "4", option1: "Oro Rosa 14k" } },
      { data: { option1: "Oro Rosa 14k", option2: "4.5" } },
      { data: { option1: "Oro Rosa 14k", option2: "5" } },
      { data: { option2: "5.5", option1: "Oro Rosa 14k" } },
      { data: { option1: "Oro Rosa 14k", option2: "6" } },
      { data: { option1: "Oro Rosa 14k", option2: "6.5" } },
      { data: { option1: "Oro Rosa 14k", option2: "7" } },
      { data: { option1: "Oro Rosa 14k", option2: "7.5" } },
      { data: { option1: "Oro Rosa 14k", option2: "8" } },
      { data: { option1: "Oro Rosa 14k", option2: "8.5" } },
      { data: { option1: "Oro Rosa 14k", option2: "9" } },
      { data: { option1: "Plata", option2: "4" } },
      { data: { option1: "Plata", option2: "4.5" } },
      { data: { option1: "Plata", option2: "5" } },
      { data: { option2: "5.5", option1: "Plata" } },
      { data: { option2: "6", option1: "Plata" } },
      { data: { option1: "Plata", option2: "6.5" } },
      { data: { option1: "Plata", option2: "7" } },
      { data: { option1: "Plata", option2: "7.5" } },
      { data: { option1: "Plata", option2: "8" } },
      { data: { option1: "Plata", option2: "8.5" } },
      { data: { option1: "Plata", option2: "9" } },
    ],
  },
  {
    isDeleted: false,
    priceRange: { maxVariantPrice: 7600, minVariantPrice: 6100 },
    productType: "Anillos",
    tags: "Anillos",
    previewImageUrl:
      "https://cdn.shopify.com/s/files/1/0612/8087/8811/files/CAMILA1.jpg?v=1684374560",
    title: "ANILLO ‘CAMILA’",
    variants: [
      { data: { option1: "Oro Blanco 14K", option2: "Rubí y Diamante" } },
      { data: { option1: "Oro Blanco 14K", option2: "Rubí y Diamante" } },
      { data: { option1: "Oro Blanco 14K", option2: "Rubí y Diamante" } },
      { data: { option1: "Oro Blanco 14K", option2: "Rubí y Diamante" } },
      { data: { option1: "Oro Blanco 14K", option2: "Rubí y Diamante" } },
      { data: { option1: "Oro Blanco 14K", option2: "Rubí y Diamante" } },
      { data: { option1: "Oro Blanco 14K", option2: "Rubí y Diamante" } },
      { data: { option1: "Oro Blanco 14K", option2: "Rubí y Diamante" } },
      { data: { option1: "Oro Blanco 14K", option2: "Rubí y Diamante" } },
      { data: { option1: "Oro Blanco 14K", option2: "Rubí y Diamante" } },
      { data: { option1: "Oro Blanco 14K", option2: "Rubí y Diamante" } },
      { data: { option1: "Oro Blanco 14K", option2: "Rubí y Moissanita" } },
      { data: { option1: "Oro Blanco 14K", option2: "Rubí y Moissanita" } },
      { data: { option1: "Oro Blanco 14K", option2: "Rubí y Moissanita" } },
      { data: { option1: "Oro Blanco 14K", option2: "Rubí y Moissanita" } },
      { data: { option1: "Oro Blanco 14K", option2: "Rubí y Moissanita" } },
      { data: { option1: "Oro Blanco 14K", option2: "Rubí y Moissanita" } },
      { data: { option1: "Oro Blanco 14K", option2: "Rubí y Moissanita" } },
      { data: { option1: "Oro Blanco 14K", option2: "Rubí y Moissanita" } },
      { data: { option1: "Oro Blanco 14K", option2: "Rubí y Moissanita" } },
      { data: { option1: "Oro Blanco 14K", option2: "Rubí y Moissanita" } },
      { data: { option1: "Oro Blanco 14K", option2: "Rubí y Moissanita" } },
      { data: { option1: "Oro Amarillo 14K", option2: "Rubí y Diamante" } },
      { data: { option1: "Oro Amarillo 14K", option2: "Rubí y Diamante" } },
      { data: { option1: "Oro Amarillo 14K", option2: "Rubí y Diamante" } },
      { data: { option1: "Oro Amarillo 14K", option2: "Rubí y Diamante" } },
      { data: { option1: "Oro Amarillo 14K", option2: "Rubí y Diamante" } },
      { data: { option1: "Oro Amarillo 14K", option2: "Rubí y Diamante" } },
      { data: { option1: "Oro Amarillo 14K", option2: "Rubí y Diamante" } },
      { data: { option1: "Oro Amarillo 14K", option2: "Rubí y Diamante" } },
      { data: { option1: "Oro Amarillo 14K", option2: "Rubí y Diamante" } },
      { data: { option1: "Oro Amarillo 14K", option2: "Rubí y Diamante" } },
      { data: { option1: "Oro Amarillo 14K", option2: "Rubí y Diamante" } },
      { data: { option1: "Oro Amarillo 14K", option2: "Rubí y Moissanita" } },
      { data: { option1: "Oro Amarillo 14K", option2: "Rubí y Moissanita" } },
      { data: { option2: "Rubí y Moissanita", option1: "Oro Amarillo 14K" } },
      { data: { option2: "Rubí y Moissanita", option1: "Oro Amarillo 14K" } },
      { data: { option1: "Oro Amarillo 14K", option2: "Rubí y Moissanita" } },
      { data: { option1: "Oro Amarillo 14K", option2: "Rubí y Moissanita" } },
      { data: { option1: "Oro Amarillo 14K", option2: "Rubí y Moissanita" } },
      { data: { option1: "Oro Amarillo 14K", option2: "Rubí y Moissanita" } },
      { data: { option1: "Oro Amarillo 14K", option2: "Rubí y Moissanita" } },
      { data: { option1: "Oro Amarillo 14K", option2: "Rubí y Moissanita" } },
      { data: { option2: "Rubí y Moissanita", option1: "Oro Amarillo 14K" } },
      { data: { option2: "Rubí y Diamante", option1: "Oro Rosa 14K" } },
      { data: { option1: "Oro Rosa 14K", option2: "Rubí y Diamante" } },
      { data: { option2: "Rubí y Diamante", option1: "Oro Rosa 14K" } },
      { data: { option2: "Rubí y Diamante", option1: "Oro Rosa 14K" } },
      { data: { option1: "Oro Rosa 14K", option2: "Rubí y Diamante" } },
      { data: { option2: "Rubí y Diamante", option1: "Oro Rosa 14K" } },
      { data: { option1: "Oro Rosa 14K", option2: "Rubí y Diamante" } },
      { data: { option1: "Oro Rosa 14K", option2: "Rubí y Diamante" } },
      { data: { option1: "Oro Rosa 14K", option2: "Rubí y Diamante" } },
      { data: { option1: "Oro Rosa 14K", option2: "Rubí y Diamante" } },
      { data: { option1: "Oro Rosa 14K", option2: "Rubí y Diamante" } },
      { data: { option1: "Oro Rosa 14K", option2: "Rubí y Moissanita" } },
      { data: { option2: "Rubí y Moissanita", option1: "Oro Rosa 14K" } },
      { data: { option1: "Oro Rosa 14K", option2: "Rubí y Moissanita" } },
      { data: { option1: "Oro Rosa 14K", option2: "Rubí y Moissanita" } },
      { data: { option1: "Oro Rosa 14K", option2: "Rubí y Moissanita" } },
      { data: { option1: "Oro Rosa 14K", option2: "Rubí y Moissanita" } },
      { data: { option1: "Oro Rosa 14K", option2: "Rubí y Moissanita" } },
      { data: { option1: "Oro Rosa 14K", option2: "Rubí y Moissanita" } },
      { data: { option1: "Oro Rosa 14K", option2: "Rubí y Moissanita" } },
      { data: { option1: "Oro Rosa 14K", option2: "Rubí y Moissanita" } },
      { data: { option1: "Oro Rosa 14K", option2: "Rubí y Moissanita" } },
    ],
    createdAt: "2023-05-17T06:36:29Z",
    descriptionHtml:
      '<meta charset="utf-8">\n<p>Este sutil y lindo anillo con piedras corte marquise es una pieza atemporal, ideal para llevarlo a diario.</p>\n<p>Nuestras piezas están hechas a mano, por lo que te pedimos tomar en cuenta un tiempo de producción de 3 – 5 semanas. Revisamos cada una de nuestras piezas y nos aseguramos de que cumplan con nuestros estándares de calidad.</p>\n<p>Utilizamos piedras naturales, por lo que el color de una pieza a otra puede variar ligeramente</p>',
    gid: "gid://shopify/Product/8030807261403",
    status: "active",
    vendor: "Mariëtte Jewelry",
    id: 8030807261403,
    options: [
      {
        _type: "option",
        name: "Metal",
        _key: "Metal",
        values: ["Oro Blanco 14K", "Oro Amarillo 14K", "Oro Rosa 14K"],
      },
      {
        _key: "Gema",
        values: ["Rubí y Diamante", "Rubí y Moissanita"],
        _type: "option",
        name: "Gema",
      },
      {
        values: [
          "4",
          "4.5",
          "5",
          "5.5",
          "6",
          "6.5",
          "7",
          "7.5",
          "8",
          "8.5",
          "9",
        ],
        _type: "option",
        name: "Talla",
        _key: "Talla",
      },
    ],
    slug: { current: "anillo-camila", _type: "slug" },
  },
  {
    tags: "Anillos",
    variants: [
      { data: { option1: "Oro Amarillo 14K", option2: "4" } },
      { data: { option2: "4.5", option1: "Oro Amarillo 14K" } },
      { data: { option1: "Oro Amarillo 14K", option2: "5" } },
      { data: { option1: "Oro Amarillo 14K", option2: "5.5" } },
      { data: { option1: "Oro Amarillo 14K", option2: "6" } },
      { data: { option1: "Oro Amarillo 14K", option2: "6.5" } },
      { data: { option1: "Oro Amarillo 14K", option2: "7" } },
      { data: { option1: "Oro Amarillo 14K", option2: "7.5" } },
      { data: { option1: "Oro Amarillo 14K", option2: "8" } },
      { data: { option1: "Oro Amarillo 14K", option2: "8.5" } },
      { data: { option1: "Oro Amarillo 14K", option2: "9" } },
      { data: { option1: "Oro Blanco 14K", option2: "4" } },
      { data: { option1: "Oro Blanco 14K", option2: "4.5" } },
      { data: { option2: "5", option1: "Oro Blanco 14K" } },
      { data: { option1: "Oro Blanco 14K", option2: "5.5" } },
      { data: { option1: "Oro Blanco 14K", option2: "6" } },
      { data: { option2: "6.5", option1: "Oro Blanco 14K" } },
      { data: { option1: "Oro Blanco 14K", option2: "7" } },
      { data: { option2: "7.5", option1: "Oro Blanco 14K" } },
      { data: { option1: "Oro Blanco 14K", option2: "8" } },
      { data: { option1: "Oro Blanco 14K", option2: "8.5" } },
      { data: { option1: "Oro Blanco 14K", option2: "9" } },
      { data: { option1: "Oro Rosa 14K", option2: "4" } },
      { data: { option1: "Oro Rosa 14K", option2: "4.5" } },
      { data: { option1: "Oro Rosa 14K", option2: "5" } },
      { data: { option1: "Oro Rosa 14K", option2: "5.5" } },
      { data: { option1: "Oro Rosa 14K", option2: "6" } },
      { data: { option1: "Oro Rosa 14K", option2: "6.5" } },
      { data: { option1: "Oro Rosa 14K", option2: "7" } },
      { data: { option2: "7.5", option1: "Oro Rosa 14K" } },
      { data: { option1: "Oro Rosa 14K", option2: "8" } },
      { data: { option1: "Oro Rosa 14K", option2: "8.5" } },
      { data: { option1: "Oro Rosa 14K", option2: "9" } },
      { data: { option2: "4", option1: "Plata" } },
      { data: { option1: "Plata", option2: "4.5" } },
      { data: { option1: "Plata", option2: "5" } },
      { data: { option1: "Plata", option2: "5.5" } },
      { data: { option2: "6", option1: "Plata" } },
      { data: { option1: "Plata", option2: "6.5" } },
      { data: { option1: "Plata", option2: "7" } },
      { data: { option1: "Plata", option2: "7.5" } },
      { data: { option1: "Plata", option2: "8" } },
      { data: { option1: "Plata", option2: "8.5" } },
      { data: { option1: "Plata", option2: "9" } },
    ],
    createdAt: "2023-05-17T06:43:21Z",
    id: 8030811259099,
    productType: "Anillos",
    slug: { current: "anillo-clara", _type: "slug" },
    descriptionHtml:
      '<meta charset="utf-8">\n<p>Este anillo es para quien ama los diseños sencillos. Con sus líneas limpias este anillo de doble banda puede llevarse solo o complementarse con otros anillos.</p>\n<p>Nuestras piezas están hechas a mano, por lo que te pedimos tomar en cuenta un tiempo de producción de 3 – 5 semanas. Revisamos cada una de nuestras piezas y nos aseguramos de que cumplan con nuestros estándares de calidad.</p>',
    isDeleted: false,
    previewImageUrl:
      "https://cdn.shopify.com/s/files/1/0612/8087/8811/files/CLARA1.jpg?v=1684374630",
    gid: "gid://shopify/Product/8030811259099",
    vendor: "Mariëtte Jewelry",
    title: "ANILLO ‘CLARA’",
    options: [
      {
        values: ["Oro Amarillo 14K", "Oro Blanco 14K", "Oro Rosa 14K", "Plata"],
        _type: "option",
        name: "Metal",
        _key: "Metal",
      },
      {
        name: "Talla",
        _key: "Talla",
        values: [
          "4",
          "4.5",
          "5",
          "5.5",
          "6",
          "6.5",
          "7",
          "7.5",
          "8",
          "8.5",
          "9",
        ],
        _type: "option",
      },
    ],
    priceRange: { maxVariantPrice: 2500, minVariantPrice: 500 },
    status: "active",
  },
  {
    tags: "Anillos",
    title: "ANILLO ‘DOT’",
    id: 8030813454555,
    status: "active",
    priceRange: { maxVariantPrice: 6300, minVariantPrice: 1 },
    slug: { current: "anillo-dot", _type: "slug" },
    gid: "gid://shopify/Product/8030813454555",
    isDeleted: false,
    vendor: "Mariëtte Jewelry",
    createdAt: "2023-05-16T23:48:35-07:00",
    descriptionHtml:
      '<meta charset="utf-8">\n<p>Sencillo y elegante, nuestro anillo Dot es muy cómodo de llevar. Puedes elegir tu piedra de nacimiento, la de un ser querido o simplemente la que más te guste para crear una pieza atemporal que combina con todo.</p>\n<p>Nuestras piezas están hechas a mano, por lo que te pedimos tomar en cuenta un tiempo de producción de 3 – 5 semanas. Revisamos cada una de nuestras piezas y nos aseguramos de que cumplan con nuestros estándares de calidad.</p>\n<p>Utilizamos piedras naturales, por lo que el color de una pieza a otra puede variar ligeramente.</p>',
    productType: "Anillos",
    variants: [
      { data: { option1: "Oro Amarillo 14K", option2: "" } },
      { data: { option1: "Oro Rosa 14k", option2: "" } },
      { data: { option1: "Oro Blanco 14k", option2: "" } },
      { data: { option1: "Plata", option2: "" } },
    ],
    options: [
      {
        values: ["Oro Amarillo 14K", "Oro Rosa 14k", "Oro Blanco 14k", "Plata"],
        _type: "option",
        name: "Material",
        _key: "Material",
      },
    ],
    previewImageUrl:
      "https://cdn.shopify.com/s/files/1/0612/8087/8811/files/DOT1.jpg?v=1684374670",
  },
  {
    tags: "Anillos",
    descriptionHtml:
      '<meta charset="utf-8">\n<p>Media churumbela Michelle pero más pequeña. Una pieza clásica atemporal que nunca pasará de moda. Hecha con 11 piedras de 2.5mm hacen de esta churumbela un elemento básico de lujo en cualquier colección de joyas.</p>\n<p>Nuestras piezas están hechas a mano, por lo que te pedimos tomar en cuenta un tiempo de producción de 3 – 5 semanas. Revisamos cada una de nuestras piezas y nos aseguramos de que cumplan con nuestros estándares de calidad.</p>\n<p>Utilizamos piedras naturales, por lo que el color de una pieza a otra puede variar ligeramente.</p>',
    id: 8030813847771,
    isDeleted: false,
    productType: "Anillos",
    title: "CHURUMBELA ‘ERIKA’",
    gid: "gid://shopify/Product/8030813847771",
    options: [
      {
        _key: "Metal",
        values: ["Oro Blanco 14K", "Oro Rosa 14K", "Oro Amarillo 14K", "Plata"],
        _type: "option",
        name: "Metal",
      },
    ],
    previewImageUrl:
      "https://cdn.shopify.com/s/files/1/0612/8087/8811/files/ERIKA1.jpg?v=1684374703",
    status: "active",
    variants: [
      { data: { option1: "Oro Blanco 14K", option2: "" } },
      { data: { option1: "Oro Rosa 14K", option2: "" } },
      { data: { option1: "Oro Amarillo 14K", option2: "" } },
      { data: { option1: "Plata", option2: "" } },
    ],
    createdAt: "2023-05-16T23:51:31-07:00",
    priceRange: { maxVariantPrice: 7700, minVariantPrice: 3500 },
    slug: { _type: "slug", current: "churumbela-erika" },
    vendor: "Mariëtte Jewelry",
  },
  {
    status: "active",
    id: 8030815125723,
    isDeleted: false,
    options: [
      {
        values: ["Oro Amarillo 14k", "Oro Rosa 14k", "Oro Blanco 14k"],
        _type: "option",
        name: "Metal",
        _key: "Metal",
      },
      {
        values: ["Zafiro y Diamantes", "Zafiro y Moissanita"],
        _type: "option",
        name: "Gema",
        _key: "Gema",
      },
      {
        name: "Tall",
        _key: "Tall",
        values: [
          "4",
          "4.5",
          "5",
          "5.5",
          "6",
          "6.5",
          "7",
          "7.5",
          "8",
          "8.5",
          "9",
        ],
        _type: "option",
      },
    ],
    priceRange: { minVariantPrice: 13800, maxVariantPrice: 16900 },
    slug: { current: "anillo-diana", _type: "slug" },
    gid: "gid://shopify/Product/8030815125723",
    previewImageUrl:
      "https://cdn.shopify.com/s/files/1/0612/8087/8811/files/DIANA1.jpg?v=1684376761",
    createdAt: "2023-05-17T06:55:47Z",
    productType: "Anillos",
    variants: [
      { data: { option2: "Zafiro y Diamantes", option1: "Oro Amarillo 14k" } },
      { data: { option1: "Oro Amarillo 14k", option2: "Zafiro y Diamantes" } },
      { data: { option1: "Oro Amarillo 14k", option2: "Zafiro y Diamantes" } },
      { data: { option1: "Oro Amarillo 14k", option2: "Zafiro y Diamantes" } },
      { data: { option2: "Zafiro y Diamantes", option1: "Oro Amarillo 14k" } },
      { data: { option1: "Oro Amarillo 14k", option2: "Zafiro y Diamantes" } },
      { data: { option1: "Oro Amarillo 14k", option2: "Zafiro y Diamantes" } },
      { data: { option1: "Oro Amarillo 14k", option2: "Zafiro y Diamantes" } },
      { data: { option1: "Oro Amarillo 14k", option2: "Zafiro y Diamantes" } },
      { data: { option1: "Oro Amarillo 14k", option2: "Zafiro y Diamantes" } },
      { data: { option1: "Oro Amarillo 14k", option2: "Zafiro y Diamantes" } },
      { data: { option1: "Oro Amarillo 14k", option2: "Zafiro y Moissanita" } },
      { data: { option1: "Oro Amarillo 14k", option2: "Zafiro y Moissanita" } },
      { data: { option1: "Oro Amarillo 14k", option2: "Zafiro y Moissanita" } },
      { data: { option1: "Oro Amarillo 14k", option2: "Zafiro y Moissanita" } },
      { data: { option1: "Oro Amarillo 14k", option2: "Zafiro y Moissanita" } },
      { data: { option1: "Oro Amarillo 14k", option2: "Zafiro y Moissanita" } },
      { data: { option2: "Zafiro y Moissanita", option1: "Oro Amarillo 14k" } },
      { data: { option2: "Zafiro y Moissanita", option1: "Oro Amarillo 14k" } },
      { data: { option1: "Oro Amarillo 14k", option2: "Zafiro y Moissanita" } },
      { data: { option1: "Oro Amarillo 14k", option2: "Zafiro y Moissanita" } },
      { data: { option2: "Zafiro y Moissanita", option1: "Oro Amarillo 14k" } },
      { data: { option1: "Oro Rosa 14k", option2: "Zafiro y Diamantes" } },
      { data: { option1: "Oro Rosa 14k", option2: "Zafiro y Diamantes" } },
      { data: { option1: "Oro Rosa 14k", option2: "Zafiro y Diamantes" } },
      { data: { option1: "Oro Rosa 14k", option2: "Zafiro y Diamantes" } },
      { data: { option1: "Oro Rosa 14k", option2: "Zafiro y Diamantes" } },
      { data: { option1: "Oro Rosa 14k", option2: "Zafiro y Diamantes" } },
      { data: { option1: "Oro Rosa 14k", option2: "Zafiro y Diamantes" } },
      { data: { option1: "Oro Rosa 14k", option2: "Zafiro y Diamantes" } },
      { data: { option2: "Zafiro y Diamantes", option1: "Oro Rosa 14k" } },
      { data: { option1: "Oro Rosa 14k", option2: "Zafiro y Diamantes" } },
      { data: { option1: "Oro Rosa 14k", option2: "Zafiro y Diamantes" } },
      { data: { option1: "Oro Rosa 14k", option2: "Zafiro y Moissanita" } },
      { data: { option1: "Oro Rosa 14k", option2: "Zafiro y Moissanita" } },
      { data: { option1: "Oro Rosa 14k", option2: "Zafiro y Moissanita" } },
      { data: { option1: "Oro Rosa 14k", option2: "Zafiro y Moissanita" } },
      { data: { option1: "Oro Rosa 14k", option2: "Zafiro y Moissanita" } },
      { data: { option2: "Zafiro y Moissanita", option1: "Oro Rosa 14k" } },
      { data: { option1: "Oro Rosa 14k", option2: "Zafiro y Moissanita" } },
      { data: { option1: "Oro Rosa 14k", option2: "Zafiro y Moissanita" } },
      { data: { option1: "Oro Rosa 14k", option2: "Zafiro y Moissanita" } },
      { data: { option1: "Oro Rosa 14k", option2: "Zafiro y Moissanita" } },
      { data: { option1: "Oro Rosa 14k", option2: "Zafiro y Moissanita" } },
      { data: { option1: "Oro Blanco 14k", option2: "Zafiro y Diamantes" } },
      { data: { option1: "Oro Blanco 14k", option2: "Zafiro y Diamantes" } },
      { data: { option1: "Oro Blanco 14k", option2: "Zafiro y Diamantes" } },
      { data: { option1: "Oro Blanco 14k", option2: "Zafiro y Diamantes" } },
      { data: { option1: "Oro Blanco 14k", option2: "Zafiro y Diamantes" } },
      { data: { option2: "Zafiro y Diamantes", option1: "Oro Blanco 14k" } },
      { data: { option1: "Oro Blanco 14k", option2: "Zafiro y Diamantes" } },
      { data: { option1: "Oro Blanco 14k", option2: "Zafiro y Diamantes" } },
      { data: { option1: "Oro Blanco 14k", option2: "Zafiro y Diamantes" } },
      { data: { option1: "Oro Blanco 14k", option2: "Zafiro y Diamantes" } },
      { data: { option1: "Oro Blanco 14k", option2: "Zafiro y Diamantes" } },
      { data: { option1: "Oro Blanco 14k", option2: "Zafiro y Moissanita" } },
      { data: { option1: "Oro Blanco 14k", option2: "Zafiro y Moissanita" } },
      { data: { option1: "Oro Blanco 14k", option2: "Zafiro y Moissanita" } },
      { data: { option2: "Zafiro y Moissanita", option1: "Oro Blanco 14k" } },
      { data: { option2: "Zafiro y Moissanita", option1: "Oro Blanco 14k" } },
      { data: { option1: "Oro Blanco 14k", option2: "Zafiro y Moissanita" } },
      { data: { option1: "Oro Blanco 14k", option2: "Zafiro y Moissanita" } },
      { data: { option1: "Oro Blanco 14k", option2: "Zafiro y Moissanita" } },
      { data: { option1: "Oro Blanco 14k", option2: "Zafiro y Moissanita" } },
      { data: { option1: "Oro Blanco 14k", option2: "Zafiro y Moissanita" } },
      { data: { option1: "Oro Blanco 14k", option2: "Zafiro y Moissanita" } },
    ],
    descriptionHtml:
      '<meta charset="utf-8">\n<p>Una pieza clásica y atemporal que representa el icónico y hermoso anillo que lució la Princesa Diana, una pieza que habla de clase y moda. Tiene un zafiro de ∼1ct como piedra central, siendo rodeado por un elegante halo de diamantes o moissanitas. El regalo perfecto para alguien que aprecia las piezas atemporales o para quien busca algo muy especial para celebrar su amor y compromiso.</p>\n<p> Nuestras piezas están hechas a mano, por lo que te pedimos tomar en cuenta un tiempo de producción de 3 – 5 semanas. Revisamos cada una de nuestras piezas y nos aseguramos de que cumplan con nuestros estándares de calidad.</p>\n<p>Utilizamos piedras naturales, a excepción de las moissanitas, por lo que el color de una pieza a otra puede variar ligeramente.</p>',
    tags: "Anillos",
    title: "ANILLO ‘DIANA’",
    vendor: "Mariëtte Jewelry",
  },
  {
    createdAt: "2023-05-17T06:58:21Z",
    descriptionHtml:
      '<meta charset="utf-8">\n<p>Al igual que la media churumbela Michelle, esta simple y clásica está hecha con 9 piedras de 3mm, pero con un twist especial, un perfil en U que le dará más brillo y luz a las piedras. Un elemento básico de lujo en cualquier colección de joyas.</p>\n<p>Nuestras piezas están hechas a mano, por lo que te pedimos tomar en cuenta un tiempo de producción de 3 – 5 semanas. Revisamos cada una de nuestras piezas y nos aseguramos de que cumplan con nuestros estándares de calidad.</p>\n<p>Utilizamos piedras naturales, por lo que el color de una pieza a otra puede variar ligeramente.</p>',
    previewImageUrl:
      "https://cdn.shopify.com/s/files/1/0612/8087/8811/files/FABIOLA1.jpg?v=1684374737",
    title: "CHURUMBELA ‘FABIOLA’",
    priceRange: { minVariantPrice: 9100, maxVariantPrice: 9100 },
    status: "active",
    vendor: "Mariëtte Jewelry",
    gid: "gid://shopify/Product/8030815355099",
    id: 8030815355099,
    isDeleted: false,
    options: [
      {
        _key: "Material",
        values: ["Oro Amarillo 14K", "Oro Rosa 14K", "Oro Blanco 14K"],
        _type: "option",
        name: "Material",
      },
    ],
    productType: "Anillos",
    slug: { current: "churumbela-fabiola", _type: "slug" },
    tags: "Anillos",
    variants: [
      { data: { option1: "Oro Amarillo 14K", option2: "" } },
      { data: { option1: "Oro Rosa 14K", option2: "" } },
      { data: { option2: "", option1: "Oro Blanco 14K" } },
    ],
  },
  {
    createdAt: "2023-05-17T15:40:21Z",
    gid: "gid://shopify/Product/8030925684955",
    productType: "Anillos",
    title: "ANILLO ‘HERA’",
    vendor: "Mariëtte Jewelry",
    descriptionHtml:
      '<meta charset="utf-8">\n<p>Los elefantes simbolizan la protección, la inteligencia y la buena fortuna. También son considerados protectores del hogar y de la familia. Lleva contigo este anillo con cinco elefantes como símbolo de la buena fortuna.</p>\n<p>Nuestras piezas están hechas a mano, por lo que te pedimos tomar en cuenta un tiempo de producción de 3 – 5 semanas. Revisamos cada una de nuestras piezas y nos aseguramos de que cumplan con nuestros estándares de calidad.</p>',
    previewImageUrl:
      "https://cdn.shopify.com/s/files/1/0612/8087/8811/files/HERA1.jpg?v=1684374777",
    status: "active",
    tags: "Anillos",
    variants: [
      { data: { option1: "Oro Amarillo 14K", option2: "4" } },
      { data: { option1: "Oro Amarillo 14K", option2: "4.5" } },
      { data: { option1: "Oro Amarillo 14K", option2: "5" } },
      { data: { option1: "Oro Amarillo 14K", option2: "5.5" } },
      { data: { option2: "6", option1: "Oro Amarillo 14K" } },
      { data: { option1: "Oro Amarillo 14K", option2: "6.5" } },
      { data: { option1: "Oro Amarillo 14K", option2: "7" } },
      { data: { option1: "Oro Amarillo 14K", option2: "7.5" } },
      { data: { option1: "Oro Amarillo 14K", option2: "8" } },
      { data: { option1: "Oro Amarillo 14K", option2: "8.5" } },
      { data: { option1: "Oro Amarillo 14K", option2: "9" } },
      { data: { option1: "Oro Blanco 14K", option2: "4" } },
      { data: { option1: "Oro Blanco 14K", option2: "4.5" } },
      { data: { option1: "Oro Blanco 14K", option2: "5" } },
      { data: { option1: "Oro Blanco 14K", option2: "5.5" } },
      { data: { option1: "Oro Blanco 14K", option2: "6" } },
      { data: { option2: "6.5", option1: "Oro Blanco 14K" } },
      { data: { option1: "Oro Blanco 14K", option2: "7" } },
      { data: { option1: "Oro Blanco 14K", option2: "7.5" } },
      { data: { option1: "Oro Blanco 14K", option2: "8" } },
      { data: { option1: "Oro Blanco 14K", option2: "8.5" } },
      { data: { option1: "Oro Blanco 14K", option2: "9" } },
      { data: { option2: "4", option1: "Oro Rosa 14K" } },
      { data: { option1: "Oro Rosa 14K", option2: "4.5" } },
      { data: { option1: "Oro Rosa 14K", option2: "5" } },
      { data: { option2: "5.5", option1: "Oro Rosa 14K" } },
      { data: { option1: "Oro Rosa 14K", option2: "6" } },
      { data: { option1: "Oro Rosa 14K", option2: "6.5" } },
      { data: { option2: "7", option1: "Oro Rosa 14K" } },
      { data: { option1: "Oro Rosa 14K", option2: "7.5" } },
      { data: { option1: "Oro Rosa 14K", option2: "8" } },
      { data: { option1: "Oro Rosa 14K", option2: "8.5" } },
      { data: { option1: "Oro Rosa 14K", option2: "9" } },
      { data: { option2: "4", option1: "Plata" } },
      { data: { option1: "Plata", option2: "4.5" } },
      { data: { option1: "Plata", option2: "5" } },
      { data: { option1: "Plata", option2: "5.5" } },
      { data: { option1: "Plata", option2: "6" } },
      { data: { option1: "Plata", option2: "6.5" } },
      { data: { option1: "Plata", option2: "7" } },
      { data: { option1: "Plata", option2: "7.5" } },
      { data: { option1: "Plata", option2: "8" } },
      { data: { option2: "8.5", option1: "Plata" } },
      { data: { option1: "Plata", option2: "9" } },
    ],
    id: 8030925684955,
    isDeleted: false,
    options: [
      {
        values: ["Oro Amarillo 14K", "Oro Blanco 14K", "Oro Rosa 14K", "Plata"],
        _type: "option",
        name: "Metal",
        _key: "Metal",
      },
      {
        name: "Talla",
        _key: "Talla",
        values: [
          "4",
          "4.5",
          "5",
          "5.5",
          "6",
          "6.5",
          "7",
          "7.5",
          "8",
          "8.5",
          "9",
        ],
        _type: "option",
      },
    ],
    priceRange: { maxVariantPrice: 2900, minVariantPrice: 500 },
    slug: { current: "anillo-hera", _type: "slug" },
  },
  {
    variants: [
      { data: { option2: "Citirno", option1: "Oro Amarillo 14K" } },
      { data: { option1: "Oro Amarillo 14K", option2: "Citirno" } },
      { data: { option1: "Oro Amarillo 14K", option2: "Citirno" } },
      { data: { option1: "Oro Amarillo 14K", option2: "Citirno" } },
      { data: { option1: "Oro Amarillo 14K", option2: "Citirno" } },
      { data: { option1: "Oro Amarillo 14K", option2: "Citirno" } },
      { data: { option1: "Oro Amarillo 14K", option2: "Citirno" } },
      { data: { option1: "Oro Amarillo 14K", option2: "Citirno" } },
      { data: { option1: "Oro Amarillo 14K", option2: "Citirno" } },
      { data: { option1: "Oro Amarillo 14K", option2: "Citirno" } },
      { data: { option1: "Oro Amarillo 14K", option2: "Citirno" } },
      { data: { option2: "Topacio Swiss Blue", option1: "Oro Amarillo 14K" } },
      { data: { option1: "Oro Amarillo 14K", option2: "Topacio Swiss Blue" } },
      { data: { option2: "Topacio Swiss Blue", option1: "Oro Amarillo 14K" } },
      { data: { option1: "Oro Amarillo 14K", option2: "Topacio Swiss Blue" } },
      { data: { option1: "Oro Amarillo 14K", option2: "Topacio Swiss Blue" } },
      { data: { option1: "Oro Amarillo 14K", option2: "Topacio Swiss Blue" } },
      { data: { option1: "Oro Amarillo 14K", option2: "Topacio Swiss Blue" } },
      { data: { option1: "Oro Amarillo 14K", option2: "Topacio Swiss Blue" } },
      { data: { option1: "Oro Amarillo 14K", option2: "Topacio Swiss Blue" } },
      { data: { option2: "Topacio Swiss Blue", option1: "Oro Amarillo 14K" } },
      { data: { option2: "Topacio Swiss Blue", option1: "Oro Amarillo 14K" } },
      { data: { option1: "Oro Blanco 14K", option2: "Citirno" } },
      { data: { option1: "Oro Blanco 14K", option2: "Citirno" } },
      { data: { option1: "Oro Blanco 14K", option2: "Citirno" } },
      { data: { option1: "Oro Blanco 14K", option2: "Citirno" } },
      { data: { option2: "Citirno", option1: "Oro Blanco 14K" } },
      { data: { option2: "Citirno", option1: "Oro Blanco 14K" } },
      { data: { option1: "Oro Blanco 14K", option2: "Citirno" } },
      { data: { option2: "Citirno", option1: "Oro Blanco 14K" } },
      { data: { option1: "Oro Blanco 14K", option2: "Citirno" } },
      { data: { option1: "Oro Blanco 14K", option2: "Citirno" } },
      { data: { option1: "Oro Blanco 14K", option2: "Citirno" } },
      { data: { option2: "Topacio Swiss Blue", option1: "Oro Blanco 14K" } },
      { data: { option1: "Oro Blanco 14K", option2: "Topacio Swiss Blue" } },
      { data: { option1: "Oro Blanco 14K", option2: "Topacio Swiss Blue" } },
      { data: { option1: "Oro Blanco 14K", option2: "Topacio Swiss Blue" } },
      { data: { option1: "Oro Blanco 14K", option2: "Topacio Swiss Blue" } },
      { data: { option1: "Oro Blanco 14K", option2: "Topacio Swiss Blue" } },
      { data: { option1: "Oro Blanco 14K", option2: "Topacio Swiss Blue" } },
      { data: { option2: "Topacio Swiss Blue", option1: "Oro Blanco 14K" } },
      { data: { option1: "Oro Blanco 14K", option2: "Topacio Swiss Blue" } },
      { data: { option1: "Oro Blanco 14K", option2: "Topacio Swiss Blue" } },
      { data: { option1: "Oro Blanco 14K", option2: "Topacio Swiss Blue" } },
      { data: { option1: "Oro Rosa 14K", option2: "Citirno" } },
      { data: { option1: "Oro Rosa 14K", option2: "Citirno" } },
      { data: { option1: "Oro Rosa 14K", option2: "Citirno" } },
      { data: { option1: "Oro Rosa 14K", option2: "Citirno" } },
      { data: { option1: "Oro Rosa 14K", option2: "Citirno" } },
      { data: { option1: "Oro Rosa 14K", option2: "Citirno" } },
      { data: { option1: "Oro Rosa 14K", option2: "Citirno" } },
      { data: { option1: "Oro Rosa 14K", option2: "Citirno" } },
      { data: { option1: "Oro Rosa 14K", option2: "Citirno" } },
      { data: { option1: "Oro Rosa 14K", option2: "Citirno" } },
      { data: { option1: "Oro Rosa 14K", option2: "Citirno" } },
      { data: { option1: "Oro Rosa 14K", option2: "Topacio Swiss Blue" } },
      { data: { option1: "Oro Rosa 14K", option2: "Topacio Swiss Blue" } },
      { data: { option1: "Oro Rosa 14K", option2: "Topacio Swiss Blue" } },
      { data: { option1: "Oro Rosa 14K", option2: "Topacio Swiss Blue" } },
      { data: { option1: "Oro Rosa 14K", option2: "Topacio Swiss Blue" } },
      { data: { option1: "Oro Rosa 14K", option2: "Topacio Swiss Blue" } },
      { data: { option1: "Oro Rosa 14K", option2: "Topacio Swiss Blue" } },
      { data: { option1: "Oro Rosa 14K", option2: "Topacio Swiss Blue" } },
      { data: { option1: "Oro Rosa 14K", option2: "Topacio Swiss Blue" } },
      { data: { option1: "Oro Rosa 14K", option2: "Topacio Swiss Blue" } },
      { data: { option1: "Oro Rosa 14K", option2: "Topacio Swiss Blue" } },
      { data: { option1: "Plata", option2: "Citirno" } },
      { data: { option2: "Citirno", option1: "Plata" } },
      { data: { option1: "Plata", option2: "Citirno" } },
      { data: { option1: "Plata", option2: "Citirno" } },
      { data: { option2: "Citirno", option1: "Plata" } },
      { data: { option1: "Plata", option2: "Citirno" } },
      { data: { option2: "Citirno", option1: "Plata" } },
      { data: { option1: "Plata", option2: "Citirno" } },
      { data: { option1: "Plata", option2: "Citirno" } },
      { data: { option1: "Plata", option2: "Citirno" } },
      { data: { option1: "Plata", option2: "Citirno" } },
      { data: { option1: "Plata", option2: "Topacio Swiss Blue" } },
      { data: { option1: "Plata", option2: "Topacio Swiss Blue" } },
      { data: { option1: "Plata", option2: "Topacio Swiss Blue" } },
      { data: { option1: "Plata", option2: "Topacio Swiss Blue" } },
      { data: { option1: "Plata", option2: "Topacio Swiss Blue" } },
      { data: { option1: "Plata", option2: "Topacio Swiss Blue" } },
      { data: { option1: "Plata", option2: "Topacio Swiss Blue" } },
      { data: { option1: "Plata", option2: "Topacio Swiss Blue" } },
      { data: { option1: "Plata", option2: "Topacio Swiss Blue" } },
      { data: { option1: "Plata", option2: "Topacio Swiss Blue" } },
      { data: { option1: "Plata", option2: "Topacio Swiss Blue" } },
    ],
    id: 8030932828379,
    priceRange: { maxVariantPrice: 1500, minVariantPrice: 1500 },
    productType: "Anillos",
    vendor: "Mariëtte Jewelry",
    title: "ANILLO ‘MARLENE’",
    createdAt: "2023-05-17T09:30:57-07:00",
    descriptionHtml:
      '<meta charset="utf-8">\n<p>Delicado y refinado, este anillo tiene una delicada banda con una piedra central en forma de gota. Este anillo es perfecto si buscas algo sencillo y elegante.</p>\n<p>Nuestras piezas están hechas a mano, por lo que te pedimos tomar en cuenta un tiempo de producción de 3 – 5 semanas. Revisamos cada una de nuestras piezas y nos aseguramos de que cumplan con nuestros estándares de calidad.</p>\n<p>Utilizamos piedras naturales, por lo que el color de una pieza a otra puede variar ligeramente.</p>',
    options: [
      {
        name: "Metal",
        _key: "Metal",
        values: ["Oro Amarillo 14K", "Oro Blanco 14K", "Oro Rosa 14K", "Plata"],
        _type: "option",
      },
      {
        _key: "Gema",
        values: ["Citirno", "Topacio Swiss Blue"],
        _type: "option",
        name: "Gema",
      },
      {
        name: "Talla",
        _key: "Talla",
        values: [
          "4",
          "4.5",
          "5",
          "5.5",
          "6",
          "6.5",
          "7",
          "7.5",
          "8",
          "8.5",
          "9",
        ],
        _type: "option",
      },
    ],
    slug: { _type: "slug", current: "anillo-marlene" },
    status: "active",
    tags: "Anillos",
    gid: "gid://shopify/Product/8030932828379",
    isDeleted: false,
    previewImageUrl:
      "https://cdn.shopify.com/s/files/1/0612/8087/8811/files/MARLENE1.jpg?v=1684374945",
  },
  {
    createdAt: "2023-05-17T16:35:49Z",
    gid: "gid://shopify/Product/8030933549275",
    options: [
      {
        _key: "Metal",
        values: ["Oro Blanco 14K", "Oro Amarillo 14K", "Oro Rosa 14K"],
        _type: "option",
        name: "Metal",
      },
      {
        _key: "Gema",
        values: ["Zafiros Rainbow"],
        _type: "option",
        name: "Gema",
      },
      {
        values: [
          "4",
          "4.5",
          "5",
          "5.5",
          "6",
          "6.5",
          "7",
          "7.5",
          "8",
          "8.5",
          "9",
        ],
        _type: "option",
        name: "Talla",
        _key: "Talla",
      },
    ],
    priceRange: { maxVariantPrice: 5700, minVariantPrice: 5700 },
    tags: "Anillos",
    isDeleted: false,
    productType: "Anillos",
    status: "active",
    variants: [
      { data: { option2: "Zafiros Rainbow", option1: "Oro Blanco 14K" } },
      { data: { option1: "Oro Blanco 14K", option2: "Zafiros Rainbow" } },
      { data: { option1: "Oro Blanco 14K", option2: "Zafiros Rainbow" } },
      { data: { option1: "Oro Blanco 14K", option2: "Zafiros Rainbow" } },
      { data: { option1: "Oro Blanco 14K", option2: "Zafiros Rainbow" } },
      { data: { option1: "Oro Blanco 14K", option2: "Zafiros Rainbow" } },
      { data: { option1: "Oro Blanco 14K", option2: "Zafiros Rainbow" } },
      { data: { option1: "Oro Blanco 14K", option2: "Zafiros Rainbow" } },
      { data: { option1: "Oro Blanco 14K", option2: "Zafiros Rainbow" } },
      { data: { option1: "Oro Blanco 14K", option2: "Zafiros Rainbow" } },
      { data: { option2: "Zafiros Rainbow", option1: "Oro Blanco 14K" } },
      { data: { option1: "Oro Amarillo 14K", option2: "Zafiros Rainbow" } },
      { data: { option1: "Oro Amarillo 14K", option2: "Zafiros Rainbow" } },
      { data: { option1: "Oro Amarillo 14K", option2: "Zafiros Rainbow" } },
      { data: { option1: "Oro Amarillo 14K", option2: "Zafiros Rainbow" } },
      { data: { option1: "Oro Amarillo 14K", option2: "Zafiros Rainbow" } },
      { data: { option1: "Oro Amarillo 14K", option2: "Zafiros Rainbow" } },
      { data: { option1: "Oro Amarillo 14K", option2: "Zafiros Rainbow" } },
      { data: { option2: "Zafiros Rainbow", option1: "Oro Amarillo 14K" } },
      { data: { option1: "Oro Amarillo 14K", option2: "Zafiros Rainbow" } },
      { data: { option2: "Zafiros Rainbow", option1: "Oro Amarillo 14K" } },
      { data: { option2: "Zafiros Rainbow", option1: "Oro Amarillo 14K" } },
      { data: { option1: "Oro Rosa 14K", option2: "Zafiros Rainbow" } },
      { data: { option1: "Oro Rosa 14K", option2: "Zafiros Rainbow" } },
      { data: { option1: "Oro Rosa 14K", option2: "Zafiros Rainbow" } },
      { data: { option1: "Oro Rosa 14K", option2: "Zafiros Rainbow" } },
      { data: { option1: "Oro Rosa 14K", option2: "Zafiros Rainbow" } },
      { data: { option1: "Oro Rosa 14K", option2: "Zafiros Rainbow" } },
      { data: { option1: "Oro Rosa 14K", option2: "Zafiros Rainbow" } },
      { data: { option1: "Oro Rosa 14K", option2: "Zafiros Rainbow" } },
      { data: { option1: "Oro Rosa 14K", option2: "Zafiros Rainbow" } },
      { data: { option1: "Oro Rosa 14K", option2: "Zafiros Rainbow" } },
      { data: { option1: "Oro Rosa 14K", option2: "Zafiros Rainbow" } },
    ],
    descriptionHtml:
      '<meta charset="utf-8">\n<p>Este anillo será la pieza central de tu look con sus zafiros de corte esmeralda. Las piedras dan un toque original y único a tu look, haciendo de esta una pieza memorable. Compuesta por 9 zafiros con un peso total aproximado de 2.4ctw</p>\n<p>Nuestras piezas están hechas a mano, por lo que te pedimos tomar en cuenta un tiempo de producción de 3 – 5 semanas. Revisamos cada una de nuestras piezas y nos aseguramos de que cumplan con nuestros estándares de calidad.</p>\n<p>Utilizamos piedras naturales, por lo que el color de una pieza a otra puede variar ligeramente.</p>',
    previewImageUrl:
      "https://cdn.shopify.com/s/files/1/0612/8087/8811/files/VICTORIA1.jpg?v=1684375072",
    title: "CHURUMBELA ‘VICTORIA’",
    id: 8030933549275,
    slug: { current: "churumbela-victoria", _type: "slug" },
    vendor: "Mariëtte Jewelry",
  },
  {
    status: "active",
    tags: "Anillos",
    vendor: "Mariëtte Jewelry",
    options: [
      {
        name: "Metal",
        _key: "Metal",
        values: ["Oro Blanco 14K", "Oro Amarillo 14K", "Oro Rosa 14K"],
        _type: "option",
      },
      {
        _type: "option",
        name: "Gema",
        _key: "Gema",
        values: ["Diamante Negro", "Lolita", "Zafiro Teal"],
      },
      {
        values: [
          "4",
          "4.5",
          "5",
          "5.5",
          "6",
          "6.5",
          "7",
          "7.5",
          "8",
          "8.5",
          "9",
        ],
        _type: "option",
        name: "Talla",
        _key: "Talla",
      },
    ],
    productType: "Anillos",
    priceRange: { maxVariantPrice: 10700, minVariantPrice: 5800 },
    descriptionHtml:
      '<meta charset="utf-8">\n<p>La Churumbela ‘Brenda’ está hecha con cinco diamantes negros en corte princesa que dan un toque especial a la pieza, haciéndola ver única. Esta churumbela lucirá espectacular en cualquier ocasión, agregando elegancia a tu atuendo de día a día o resaltando un atuendo para un evento especial.</p>\n<p>Nuestras piezas están hechas a mano, por lo que te pedimos tomar en cuenta un tiempo de producción de 3 – 5 semanas. Revisamos cada una de nuestras piezas y nos aseguramos de que cumplan con nuestros estándares de calidad.</p>\n<p>Utilizamos piedras naturales, por lo que el color de una pieza a otra puede variar ligeramente.</p>',
    isDeleted: false,
    title: "CHURUMBELA ‘BRENDA’",
    variants: [
      { data: { option1: "Oro Blanco 14K", option2: "Diamante Negro" } },
      { data: { option1: "Oro Blanco 14K", option2: "Diamante Negro" } },
      { data: { option1: "Oro Blanco 14K", option2: "Diamante Negro" } },
      { data: { option1: "Oro Blanco 14K", option2: "Diamante Negro" } },
      { data: { option1: "Oro Blanco 14K", option2: "Diamante Negro" } },
      { data: { option1: "Oro Blanco 14K", option2: "Diamante Negro" } },
      { data: { option1: "Oro Blanco 14K", option2: "Diamante Negro" } },
      { data: { option1: "Oro Blanco 14K", option2: "Diamante Negro" } },
      { data: { option1: "Oro Blanco 14K", option2: "Diamante Negro" } },
      { data: { option1: "Oro Blanco 14K", option2: "Diamante Negro" } },
      { data: { option1: "Oro Blanco 14K", option2: "Diamante Negro" } },
      { data: { option1: "Oro Blanco 14K", option2: "Lolita" } },
      { data: { option1: "Oro Blanco 14K", option2: "Lolita" } },
      { data: { option1: "Oro Blanco 14K", option2: "Lolita" } },
      { data: { option1: "Oro Blanco 14K", option2: "Lolita" } },
      { data: { option1: "Oro Blanco 14K", option2: "Lolita" } },
      { data: { option1: "Oro Blanco 14K", option2: "Lolita" } },
      { data: { option1: "Oro Blanco 14K", option2: "Lolita" } },
      { data: { option1: "Oro Blanco 14K", option2: "Lolita" } },
      { data: { option1: "Oro Blanco 14K", option2: "Lolita" } },
      { data: { option2: "Lolita", option1: "Oro Blanco 14K" } },
      { data: { option1: "Oro Blanco 14K", option2: "Lolita" } },
      { data: { option1: "Oro Blanco 14K", option2: "Zafiro Teal" } },
      { data: { option1: "Oro Blanco 14K", option2: "Zafiro Teal" } },
      { data: { option2: "Zafiro Teal", option1: "Oro Blanco 14K" } },
      { data: { option1: "Oro Blanco 14K", option2: "Zafiro Teal" } },
      { data: { option1: "Oro Blanco 14K", option2: "Zafiro Teal" } },
      { data: { option2: "Zafiro Teal", option1: "Oro Blanco 14K" } },
      { data: { option2: "Zafiro Teal", option1: "Oro Blanco 14K" } },
      { data: { option1: "Oro Blanco 14K", option2: "Zafiro Teal" } },
      { data: { option1: "Oro Blanco 14K", option2: "Zafiro Teal" } },
      { data: { option1: "Oro Blanco 14K", option2: "Zafiro Teal" } },
      { data: { option1: "Oro Blanco 14K", option2: "Zafiro Teal" } },
      { data: { option1: "Oro Amarillo 14K", option2: "Diamante Negro" } },
      { data: { option1: "Oro Amarillo 14K", option2: "Diamante Negro" } },
      { data: { option1: "Oro Amarillo 14K", option2: "Diamante Negro" } },
      { data: { option1: "Oro Amarillo 14K", option2: "Diamante Negro" } },
      { data: { option1: "Oro Amarillo 14K", option2: "Diamante Negro" } },
      { data: { option1: "Oro Amarillo 14K", option2: "Diamante Negro" } },
      { data: { option1: "Oro Amarillo 14K", option2: "Diamante Negro" } },
      { data: { option1: "Oro Amarillo 14K", option2: "Diamante Negro" } },
      { data: { option1: "Oro Amarillo 14K", option2: "Diamante Negro" } },
      { data: { option1: "Oro Amarillo 14K", option2: "Diamante Negro" } },
      { data: { option1: "Oro Amarillo 14K", option2: "Diamante Negro" } },
      { data: { option1: "Oro Amarillo 14K", option2: "Lolita" } },
      { data: { option1: "Oro Amarillo 14K", option2: "Lolita" } },
      { data: { option2: "Lolita", option1: "Oro Amarillo 14K" } },
      { data: { option1: "Oro Amarillo 14K", option2: "Lolita" } },
      { data: { option1: "Oro Amarillo 14K", option2: "Lolita" } },
      { data: { option2: "Lolita", option1: "Oro Amarillo 14K" } },
      { data: { option1: "Oro Amarillo 14K", option2: "Lolita" } },
      { data: { option2: "Lolita", option1: "Oro Amarillo 14K" } },
      { data: { option1: "Oro Amarillo 14K", option2: "Lolita" } },
      { data: { option1: "Oro Amarillo 14K", option2: "Lolita" } },
      { data: { option1: "Oro Amarillo 14K", option2: "Lolita" } },
      { data: { option1: "Oro Amarillo 14K", option2: "Zafiro Teal" } },
      { data: { option1: "Oro Amarillo 14K", option2: "Zafiro Teal" } },
      { data: { option1: "Oro Amarillo 14K", option2: "Zafiro Teal" } },
      { data: { option1: "Oro Amarillo 14K", option2: "Zafiro Teal" } },
      { data: { option1: "Oro Amarillo 14K", option2: "Zafiro Teal" } },
      { data: { option1: "Oro Amarillo 14K", option2: "Zafiro Teal" } },
      { data: { option1: "Oro Amarillo 14K", option2: "Zafiro Teal" } },
      { data: { option1: "Oro Amarillo 14K", option2: "Zafiro Teal" } },
      { data: { option1: "Oro Amarillo 14K", option2: "Zafiro Teal" } },
      { data: { option1: "Oro Amarillo 14K", option2: "Zafiro Teal" } },
      { data: { option1: "Oro Amarillo 14K", option2: "Zafiro Teal" } },
      { data: { option1: "Oro Rosa 14K", option2: "Diamante Negro" } },
      { data: { option1: "Oro Rosa 14K", option2: "Diamante Negro" } },
      { data: { option1: "Oro Rosa 14K", option2: "Diamante Negro" } },
      { data: { option2: "Diamante Negro", option1: "Oro Rosa 14K" } },
      { data: { option1: "Oro Rosa 14K", option2: "Diamante Negro" } },
      { data: { option1: "Oro Rosa 14K", option2: "Diamante Negro" } },
      { data: { option1: "Oro Rosa 14K", option2: "Diamante Negro" } },
      { data: { option2: "Diamante Negro", option1: "Oro Rosa 14K" } },
      { data: { option1: "Oro Rosa 14K", option2: "Diamante Negro" } },
      { data: { option1: "Oro Rosa 14K", option2: "Diamante Negro" } },
      { data: { option1: "Oro Rosa 14K", option2: "Diamante Negro" } },
      { data: { option1: "Oro Rosa 14K", option2: "Lolita" } },
      { data: { option1: "Oro Rosa 14K", option2: "Lolita" } },
      { data: { option1: "Oro Rosa 14K", option2: "Lolita" } },
      { data: { option1: "Oro Rosa 14K", option2: "Lolita" } },
      { data: { option1: "Oro Rosa 14K", option2: "Lolita" } },
      { data: { option1: "Oro Rosa 14K", option2: "Lolita" } },
      { data: { option1: "Oro Rosa 14K", option2: "Lolita" } },
      { data: { option1: "Oro Rosa 14K", option2: "Lolita" } },
      { data: { option1: "Oro Rosa 14K", option2: "Lolita" } },
      { data: { option1: "Oro Rosa 14K", option2: "Lolita" } },
      { data: { option1: "Oro Rosa 14K", option2: "Lolita" } },
      { data: { option1: "Oro Rosa 14K", option2: "Zafiro Teal" } },
      { data: { option1: "Oro Rosa 14K", option2: "Zafiro Teal" } },
      { data: { option1: "Oro Rosa 14K", option2: "Zafiro Teal" } },
      { data: { option1: "Oro Rosa 14K", option2: "Zafiro Teal" } },
      { data: { option1: "Oro Rosa 14K", option2: "Zafiro Teal" } },
      { data: { option2: "Zafiro Teal", option1: "Oro Rosa 14K" } },
      { data: { option2: "Zafiro Teal", option1: "Oro Rosa 14K" } },
      { data: { option1: "Oro Rosa 14K", option2: "Zafiro Teal" } },
      { data: { option1: "Oro Rosa 14K", option2: "Zafiro Teal" } },
      { data: { option1: "Oro Rosa 14K", option2: "Zafiro Teal" } },
      { data: { option1: "Oro Rosa 14K", option2: "Zafiro Teal" } },
    ],
    gid: "gid://shopify/Product/8030935056603",
    slug: { current: "churumbela-brenda", _type: "slug" },
    previewImageUrl:
      "https://cdn.shopify.com/s/files/1/0612/8087/8811/files/BRENDA1.jpg?v=1684376721",
    createdAt: "2023-05-17T16:45:02Z",
    id: 8030935056603,
  },
  {
    status: "active",
    priceRange: { maxVariantPrice: 8300, minVariantPrice: 6600 },
    slug: { current: "anillo-nuit", _type: "slug" },
    id: 8030936662235,
    title: "ANILLO ‘NUIT’",
    vendor: "Mariëtte Jewelry",
    createdAt: "2023-05-17T16:55:24Z",
    descriptionHtml:
      '<meta charset="utf-8">\n<p>Un accesorio moderno que puede combinarse con todos tus conjuntos, este anillo grueso presenta cinco gemas para formar una constelación. Disponible en oro y plata, este anillo aportará estilo a todos tus conjuntos, tanto si te vistes de forma elegante como informal.</p>\n<p>Nuestras piezas están hechas a mano, por lo que te pedimos tomar en cuenta un tiempo de producción de 3 – 5 semanas. Revisamos cada una de nuestras piezas y nos aseguramos de que cumplan con nuestros estándares de calidad.</p>\n<p>Utilizamos piedras naturales, por lo que el color de una pieza a otra puede variar ligeramente.</p>',
    options: [
      {
        values: ["Oro Amarillo 14K", "Oro Blanco 15K", "Oro Rosa 14K"],
        _type: "option",
        name: "Metal",
        _key: "Metal",
      },
      {
        _type: "option",
        name: "Gema",
        _key: "Gema",
        values: ["Diamate", "Moissanita", "Zafiro Rosa"],
      },
      {
        _key: "Talla",
        values: [
          "4",
          "4.5",
          "5",
          "5.5",
          "6",
          "6.5",
          "7",
          "7.5",
          "8",
          "8.5",
          "9",
        ],
        _type: "option",
        name: "Talla",
      },
    ],
    previewImageUrl:
      "https://cdn.shopify.com/s/files/1/0612/8087/8811/files/NUIT2.jpg?v=1684342530",
    productType: "Anillos",
    tags: "Anillos",
    variants: [
      { data: { option1: "Oro Amarillo 14K", option2: "Diamate" } },
      { data: { option1: "Oro Amarillo 14K", option2: "Diamate" } },
      { data: { option2: "Diamate", option1: "Oro Amarillo 14K" } },
      { data: { option1: "Oro Amarillo 14K", option2: "Diamate" } },
      { data: { option1: "Oro Amarillo 14K", option2: "Diamate" } },
      { data: { option1: "Oro Amarillo 14K", option2: "Diamate" } },
      { data: { option1: "Oro Amarillo 14K", option2: "Diamate" } },
      { data: { option1: "Oro Amarillo 14K", option2: "Diamate" } },
      { data: { option1: "Oro Amarillo 14K", option2: "Diamate" } },
      { data: { option1: "Oro Amarillo 14K", option2: "Diamate" } },
      { data: { option1: "Oro Amarillo 14K", option2: "Diamate" } },
      { data: { option1: "Oro Amarillo 14K", option2: "Moissanita" } },
      { data: { option1: "Oro Amarillo 14K", option2: "Moissanita" } },
      { data: { option1: "Oro Amarillo 14K", option2: "Moissanita" } },
      { data: { option1: "Oro Amarillo 14K", option2: "Moissanita" } },
      { data: { option1: "Oro Amarillo 14K", option2: "Moissanita" } },
      { data: { option1: "Oro Amarillo 14K", option2: "Moissanita" } },
      { data: { option2: "Moissanita", option1: "Oro Amarillo 14K" } },
      { data: { option1: "Oro Amarillo 14K", option2: "Moissanita" } },
      { data: { option1: "Oro Amarillo 14K", option2: "Moissanita" } },
      { data: { option1: "Oro Amarillo 14K", option2: "Moissanita" } },
      { data: { option1: "Oro Amarillo 14K", option2: "Moissanita" } },
      { data: { option2: "Zafiro Rosa", option1: "Oro Amarillo 14K" } },
      { data: { option1: "Oro Amarillo 14K", option2: "Zafiro Rosa" } },
      { data: { option1: "Oro Amarillo 14K", option2: "Zafiro Rosa" } },
      { data: { option1: "Oro Amarillo 14K", option2: "Zafiro Rosa" } },
      { data: { option1: "Oro Amarillo 14K", option2: "Zafiro Rosa" } },
      { data: { option1: "Oro Amarillo 14K", option2: "Zafiro Rosa" } },
      { data: { option2: "Zafiro Rosa", option1: "Oro Amarillo 14K" } },
      { data: { option1: "Oro Amarillo 14K", option2: "Zafiro Rosa" } },
      { data: { option1: "Oro Amarillo 14K", option2: "Zafiro Rosa" } },
      { data: { option1: "Oro Amarillo 14K", option2: "Zafiro Rosa" } },
      { data: { option1: "Oro Amarillo 14K", option2: "Zafiro Rosa" } },
      { data: { option1: "Oro Blanco 15K", option2: "Diamate" } },
      { data: { option1: "Oro Blanco 15K", option2: "Diamate" } },
      { data: { option1: "Oro Blanco 15K", option2: "Diamate" } },
      { data: { option1: "Oro Blanco 15K", option2: "Diamate" } },
      { data: { option1: "Oro Blanco 15K", option2: "Diamate" } },
      { data: { option1: "Oro Blanco 15K", option2: "Diamate" } },
      { data: { option1: "Oro Blanco 15K", option2: "Diamate" } },
      { data: { option1: "Oro Blanco 15K", option2: "Diamate" } },
      { data: { option1: "Oro Blanco 15K", option2: "Diamate" } },
      { data: { option1: "Oro Blanco 15K", option2: "Diamate" } },
      { data: { option1: "Oro Blanco 15K", option2: "Diamate" } },
      { data: { option2: "Moissanita", option1: "Oro Blanco 15K" } },
      { data: { option1: "Oro Blanco 15K", option2: "Moissanita" } },
      { data: { option1: "Oro Blanco 15K", option2: "Moissanita" } },
      { data: { option1: "Oro Blanco 15K", option2: "Moissanita" } },
      { data: { option1: "Oro Blanco 15K", option2: "Moissanita" } },
      { data: { option1: "Oro Blanco 15K", option2: "Moissanita" } },
      { data: { option1: "Oro Blanco 15K", option2: "Moissanita" } },
      { data: { option1: "Oro Blanco 15K", option2: "Moissanita" } },
      { data: { option1: "Oro Blanco 15K", option2: "Moissanita" } },
      { data: { option2: "Moissanita", option1: "Oro Blanco 15K" } },
      { data: { option1: "Oro Blanco 15K", option2: "Moissanita" } },
      { data: { option1: "Oro Blanco 15K", option2: "Zafiro Rosa" } },
      { data: { option1: "Oro Blanco 15K", option2: "Zafiro Rosa" } },
      { data: { option2: "Zafiro Rosa", option1: "Oro Blanco 15K" } },
      { data: { option1: "Oro Blanco 15K", option2: "Zafiro Rosa" } },
      { data: { option1: "Oro Blanco 15K", option2: "Zafiro Rosa" } },
      { data: { option1: "Oro Blanco 15K", option2: "Zafiro Rosa" } },
      { data: { option1: "Oro Blanco 15K", option2: "Zafiro Rosa" } },
      { data: { option2: "Zafiro Rosa", option1: "Oro Blanco 15K" } },
      { data: { option1: "Oro Blanco 15K", option2: "Zafiro Rosa" } },
      { data: { option1: "Oro Blanco 15K", option2: "Zafiro Rosa" } },
      { data: { option1: "Oro Blanco 15K", option2: "Zafiro Rosa" } },
      { data: { option1: "Oro Rosa 14K", option2: "Diamate" } },
      { data: { option1: "Oro Rosa 14K", option2: "Diamate" } },
      { data: { option1: "Oro Rosa 14K", option2: "Diamate" } },
      { data: { option1: "Oro Rosa 14K", option2: "Diamate" } },
      { data: { option1: "Oro Rosa 14K", option2: "Diamate" } },
      { data: { option1: "Oro Rosa 14K", option2: "Diamate" } },
      { data: { option1: "Oro Rosa 14K", option2: "Diamate" } },
      { data: { option1: "Oro Rosa 14K", option2: "Diamate" } },
      { data: { option1: "Oro Rosa 14K", option2: "Diamate" } },
      { data: { option1: "Oro Rosa 14K", option2: "Diamate" } },
      { data: { option1: "Oro Rosa 14K", option2: "Diamate" } },
      { data: { option1: "Oro Rosa 14K", option2: "Moissanita" } },
      { data: { option1: "Oro Rosa 14K", option2: "Moissanita" } },
      { data: { option1: "Oro Rosa 14K", option2: "Moissanita" } },
      { data: { option1: "Oro Rosa 14K", option2: "Moissanita" } },
      { data: { option2: "Moissanita", option1: "Oro Rosa 14K" } },
      { data: { option1: "Oro Rosa 14K", option2: "Moissanita" } },
      { data: { option2: "Moissanita", option1: "Oro Rosa 14K" } },
      { data: { option1: "Oro Rosa 14K", option2: "Moissanita" } },
      { data: { option1: "Oro Rosa 14K", option2: "Moissanita" } },
      { data: { option2: "Moissanita", option1: "Oro Rosa 14K" } },
      { data: { option1: "Oro Rosa 14K", option2: "Moissanita" } },
      { data: { option1: "Oro Rosa 14K", option2: "Zafiro Rosa" } },
      { data: { option1: "Oro Rosa 14K", option2: "Zafiro Rosa" } },
      { data: { option1: "Oro Rosa 14K", option2: "Zafiro Rosa" } },
      { data: { option1: "Oro Rosa 14K", option2: "Zafiro Rosa" } },
      { data: { option1: "Oro Rosa 14K", option2: "Zafiro Rosa" } },
      { data: { option1: "Oro Rosa 14K", option2: "Zafiro Rosa" } },
      { data: { option1: "Oro Rosa 14K", option2: "Zafiro Rosa" } },
      { data: { option1: "Oro Rosa 14K", option2: "Zafiro Rosa" } },
      { data: { option1: "Oro Rosa 14K", option2: "Zafiro Rosa" } },
      { data: { option2: "Zafiro Rosa", option1: "Oro Rosa 14K" } },
      { data: { option1: "Oro Rosa 14K", option2: "Zafiro Rosa" } },
    ],
    gid: "gid://shopify/Product/8030936662235",
    isDeleted: false,
  },
];
